### ISSUE TITLE
[Bundle] Boost create subdir

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/remaken#1]
On Windows, Remaken bundle command fails if destination directory (only for subdir) doesn't exist : add recursivity argument

`remaken bundle -d ./dir/subdir --cpp-std 17 -b cl-14.1 packagedependencies.txt`

![image](https://user-images.githubusercontent.com/22341309/85111560-cc021500-b214-11ea-8a29-d77b3e951d59.png)

**Comment by Firefly35** [comment]
Fixed in https://github.com/b-com-software-basis/remaken/tree/1.6.2
