### ISSUE TITLE
Windows setup wizard typo: replace 'overrided' by 'overridden'

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#11]
https://github.com/b-com-software-basis/remaken/blob/648ec9c569aab588a6327ed80debc688a9d0db1a/resources/install_remaken_3rdparties.nsh#L210

**Comment by stefled** [comment]
will be fixed in 1.9.3
commit : 668e55352306592dce6bf239b59e4bb12df71f82

**Comment by stefled** [comment]
released in 1.9.3
