### ISSUE TITLE
Handle header-only libraries so that they don't get downloaded every time

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#14]
For example, when referencing spdlog located in this github repo:
`https://github.com/SolarFramework/binaries/releases/tag/spdlog%2F0.14.0%2Fwin`

with
`spdlog|0.14.0|spdlog|thirdParties@github|https://github.com/SolarFramework/binaries/releases/download`

I get this log everytime I call remaken install:
```
=> Installing github::https://github.com/SolarFramework/binaries/releases/download/spdlog/0.14.0/win/spdlog_0.14.0_x86_64_shared_release.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   647  100   647    0     0    647      0  0:00:01 --:--:--  0:00:01  1182
100 95248  100 95248    0     0  95248      0  0:00:01 --:--:--  0:00:01 95248
===> spdlog installed in "C:/Users/foo/.remaken/packages\thirdParties\win-cl-14.1\spdlog\0.14.0"
```

**Comment by stefled** [comment]
for remaken dependencies, you can add an empty `.pkginfo` folder in the dependency.
Then : 
- `.headers` subfolder specifies that dependency contains headers
- `.lib` subfolder specifies that dependency contains libraries
-`.bin` subfolder specifies that dependency contains binairies

by default, `.pkginfo` folder is not present on remaken dependency (optionnal).
Uses remaken packages for set up .pkginfo folder automatically.

For your example, you can add `.pkginfo\.headers` folders in C:/Users/foo/.remaken/packages\thirdParties\win-cl-14.1\spdlog\0.14.0, and then re-package spdlog manually if you want.
