### ISSUE TITLE
Add support for non interactive condition handling + update/fix README ?

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#15]
When `remaken install` is called on a project using library conditions (such as [this one](https://github.com/SolarFramework/SolARModuleFBOW/blob/develop/packagedependencies.txt)), process is interactive, and stops to ask user whether each configuration should be used or not.

This is not desirable in every situation, e.g. for long lasting builds or with a CI server.
In these situations, it would be nice to have a way to specify the answers in advance, as done by `apt-get -y install`, to switch to a non-interactive mode.

It could be done for example by setting env vars of the same names ?

If it is already possible, sorry for the noise, I didn't find it in the README page.
Maybe it was intended to be [here](https://github.com/b-com-software-basis/remaken#installing-dependencies) ? (`add conditions configuration description`).

Also, the line syntax is described [here](https://github.com/b-com-software-basis/remaken#line-syntax) as:

`framework#channel | version | [condition]%library name | identifier@repository_type | repository_url | link_mode | options`

But in [this project](https://github.com/SolarFramework/SolARModuleFBOW/blob/develop/packagedependencies.txt), the condition seems to be after the library name. Is this a mistake?

Thanks.

**Comment by stefled** [comment]
released in remaken 1.9.3
