### ISSUE TITLE
[bundleXpcf] Add way to treat missing library as an error 

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#16]
**PROBLEM**
Our CI packages sample apps using `remaken bundleXpcf`.
If a dependency library is missing somehow, a warning message is the only indication that it happened:
```
[warning] Ignoring SolARPipeline_FiducialMarker dependency: no shared library found from "c:/Users/ContainerAdministrator/.remaken/packages/win-cl-14.1\SolARBuild\SolARPipeline_FiducialMarker\0.11.0\lib\x86_64\shared\release"
```

Thus, the CI will go on with the process of packaging the sample whereas there's no way it leads to something executable.

**FEATURE REQUEST**
Add a way to raise an error (interruption + exit status) when such a situation occurs.

**SUGGESTED SOLUTION**
* Make it an error by default.
* Optionally add an `--ignore`/`--force` flag of some sort if we still want the "warning" behavior.

**CAUTION**
We also get this error message from header only library.
```
[warning] Ignoring spdlog dependency: no shared library found from "/home/jenkins/.remaken/packages/linux-gcc/thirdParties/spdlog/0.14.0/lib/x86_64/shared/debug"
```
Not finding a shared lib is expected so we don't want an error in this case.

You already mentionned a fix for header-only libs like this regarding  `remaken install` installing them over and over again, by adding a the following directories `.pkginfo/.headers` in the library package.
I've tested it, and it works on `remaken install` but I didn't pushed the fix in the deployed library, so I don't know, but it may allow to solve the problem exposed in the CAUTION section above... 
I'll update the issue if it does, so you don't have to make a special case for header-only libraries.

Thanks.

**Comment by stefled** [comment]
### A solution proposed for Remaken bundle : 

add an` ignore-errors` command line paramater for display warning for a dependency without lib dir
	example : "Ignoring bundle artefact error : %dep_name% dependency: no shared library found from %dep_lib_path%
else if dependency has no lib folder:
	- if dependency is header only (contains `.pkginfo/.headers` folder and no `.pkginfo/.lib`) then display an info message like "Ignoring %dep_name% dependency: header only library"
	- if dependency contains `.pkginfo/.lib` folder then thow a runtime error like "Error: %dep_name% dependency:  no shared library found from %dep_lib_path%"
	- if dependency doesn't contains .pkginfo/.lib folder then raise a runtime error like "Error %dep_name% dependency : no shared library found from %dep_lib_path% and no `.pkginfo/.lib` folder found from %dep_root_path%

### For remaken bundleXpcf:
also add `ignore-errors` command line parameter with the same behaviour (warning instead raising an error)

I don't believe that there are error or a warning when Xpcf modules shared librairies folder are not found.
Xpcf runtime dependencies are managed diffenrently than compiled time shared librairies : we only get the shared lib folder.
We can add a test for check shared lib folder existence
if this folder doesn't exist 
- display a warning when ignore-errors param is set : "Ignoring bundleXpcf artefact error: shared library %lib_path% folder not found"
- else raise a runtime error : "Error : bundleXpcf: shared library %lib_path% folder not found"

**Comment by stefled** [comment]
A bug fix corresponding to the last comment has been committed (cf #3f5273ec3b7fbe57851640c9160729d24e134bcd ) on Remaken, and bd/qmake (commit #ffd5c6cc5b746b2e60bb0676d7b83558a11820af )

available in the next version of remake and bd/qmake
