### ISSUE TITLE
Add way to create native remaken pkg-config-based package

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#17]
Currently, scripts that help create such packages exists in the SolARFramework project here:
https://github.com/SolarFramework/Tools/releases/tag/ArtifactPackager

After discussing the matter, it has been agreed that It could make sense to distribute those scripts along with remaken so it can benefit to other remaken users as well, until a `remaken package` subcommand is implemented eventually.

**Comment by stefled** [comment]
Scripts have been updated (for .pkginfo / .headers/.lib/.bin folders) and added to remaken repository : 
[875e57457bbbfb667fc31cab24a2ca513255b2d5](https://github.com/b-com-software-basis/remaken/commit/875e57457bbbfb667fc31cab24a2ca513255b2d5)

A new release tag [ArtifactPackager](https://github.com/b-com-software-basis/remaken/releases/tag/artifactpackager) has been added with these scripts

`Remaken init artefactpkg [--tag]`  command allow to install script for current OS (tag can be used for specify the release tag) : cf [2c49448a6d7bcbabbadcdaa5dda54a66b98f6f5c](https://github.com/b-com-software-basis/remaken/commit/2c49448a6d7bcbabbadcdaa5dda54a66b98f6f5c)

Remaken documentation has been updated for describes [third parties packaging](https://github.com/b-com-software-basis/remaken/tree/develop#packaging-your-third-parties) and the new `init artefactpkg` subcommand
