### ISSUE TITLE
Specifying conan remote in packagedependencies.txt has no effect

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#18]
**HOW TO REPRODUCE**
* checkout [SolARFramework](https://github.com/SolarFramework/SolARFramework)
* remove `conan-solar` remote if it exists with `conan remote remove conan-solar`
* check it does not exists with `conan remote list`
* call `remaken install`

`packagedependencies-linux.txt` specifies a conan remote:
```
openimageio|2.3.13.0|openimageio|conan-solar@conan|conan-solar#https://repository.solarframework.org/conan#0|default|boost:shared=True#boost:zlib=False#boost:bzip2=False#boost:numa=False#boost:without_stacktrace=True#with_ffmpeg=False#with_freetype=False#with_giflib=False#with_hdf5=False#with_libheif=False#with_libwebp=False#with_opencolorio=False#with_opencv=False#with_ptex=False#with_tools=False
```

**EXPECTED BEHAVIOR**
* remote is added
* dependencies are installed from this remote

**OBSERVED BEHAVIOR**
* trace indicate that remote is added
```
Adding conan remote: conan-solar position: 0
```
* but depedency is not found:
```
openimageio/2.3.13.0@conan-solar/stable: Not found in local cache, looking in remotes...
openimageio/2.3.13.0@conan-solar/stable: Trying with 'conan-solar-old'...
```
```
 $ conan remote list
conan-solar-old: https://XXX [Verify SSL: True]
conan-bcom: https://YYY [Verify SSL: True]
conancenter: https://center.conan.io [Verify SSL: True]
```

**Comment by stefled** [comment]
Bug reproduced

A conan remote is only added if not already exists, but this is based on "name", and the problem to add `conan-solar` is because `conan-solar-old` already exists and contains a part of the name.
A fix will be added in order to check the whole name

fix in next version 1.9.4

Currently you can remove `conan-solar-old` or rename with another remote name.
