### ISSUE TITLE
"[warning] Unable to add conan remote." when no intention of specifying a remote

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#19]
**HOW TO REPRODUCE**
* checkout [SolARFramework](https://github.com/SolarFramework/SolARFramework)
* call `remaken install`

**EXPECTED BEHAVIOR**
* installs dependencies without issue

**OBSERVED BEHAVIOR**
* Warning:

```
$ remaken install
=> Installing conan::eigen/3.3.9@|linux-gcc|x86_64|17|shared|release|
[2022-12-13 12:08:40.028960] [0x00007f06179fc740] [warning] Unable to add conan remote. Remote format must follow remoteAlias#remoteURL[#position]. Missing one of remoteAlias or remoteURL: conan-center
```

Seems related to eigen dependency,  defined as:
```
eigen|3.3.9|eigen|conan|conan-center|na|
```

Is the synctax incorrect, or is should there be no warning message?

**Comment by stefled** [comment]
The warning message is correct. 
It's just a message that informs you that you don't have specified your `repository_url` for add conan remote and explains how to add it : 
_"Remote format must follow remoteAlias#remoteURL[#position]"_

For instance, with eigen, you can simply modify your packagedependencies.txt with :
`eigen|3.3.9|eigen|conan|conancenter#https://center.conan.io|na|`
(note that position has not been added here, but you can specified it if you want)

Please also note that `conancenter` is the main official repository, and `conan-center `has been deprecated (cf [conan doc](https://docs.conan.io/en/latest/uploading_packages/remotes.html#conancenter)). 

Remaken and builddefs/qmake continue to manage the deprecated remote `conan-center`, but a fix is under development when this `remoteAlias` is used with a `remoteURL` (it's only with conan-center or conancenter, but not on custom remote names)

The warning message will also be updated to agree with the terms of the [Remaken documentation](https://github.com/b-com-software-basis/remaken#fields-specifications) : 
_Unable to add conan remote. Remote format must follow repository_identifier#repository_url[#position]. Missing one of repository_identifier or repository_url:_

**Comment by jim-bcom** [comment]
* OK, so from the (first) warning message, and your answer, it seems that the expected way of specifying conan remote should be to give alias+URL, is that correct ?
Personnally I'd rather use only the alias by default as it's way easier to maintain. The URLs are centralized in conan remotes, so it's easy to change for all projects at once instead of keeping potentially many projects in sync.
* If the previous assumption is correct, it seems odd to allow to not specify the URL. The warning message states that `Remote format must follow  remoteAlias#remoteURL[#position]`: from this syntax, only `position` seems optional. So either specifying the URL is mandatory to comply to the specified syntax, or it is authorized to only specify the alias, but in that case, we shouldn't get any message about a failure to add a remote: not specifying a URL should mean "use the existing repo" or raise an error if it does not exist. Without a URL the remote can obviously not be added.
* The updated message is a bit odd: `Unable to add conan remote. Remote format must follow repository_identifier#repository_url[#position]. Missing one of repository_identifier or repository_url:`
  * Again, it seems that the URL must be specified from the syntax description.
  * But the end of the message suggests that either the alias or the URL is missing. I get that we can use the alias without specifying the URL, but the other way around ? Can you replace the alias by the URL when working with conan ? If not this message is maybe misleading.

* to summarize, the way I would expected it to work is
  * follow this syntax instead: `remoteAlias[#remoteURL[#position]]`
  * `remoteAlias`: use existing alias, error otherwise
  * `remoteAlias#remoteURL[#position]`: add conan remote. Question: what's the behavior of this ?
    * Add repo if it does not exist, keep old one otherwise (+ warning)?
    * Overwrites the existing repos (+warning) ?
    * Don't actually alter `conan remote list`, but use the info only for the associated dependency.
 The first 2 sounds error-prone to me: again, if many subprojects have out of sync aliases/URLS, the behavior becomes quite unpredicatable.

I must say I'm not sure I'm fond of this feature, except maybe if it follows the behavior of the 3rd bullet.
That's why I'd prefer to be using only alias, without warning messages (even if the URL feature exists).

**Comment by stefled** [comment]
- Specify remote Alias and remote Url is a alternative solution for add conan remote for conan dependencies in a packagedependencies.txt. 
You can also keep only the remote Alias without remote Url, and I understand it is easier to maintain conan remotes for multiples projects and subprojects with conventionnals conan commands.

- Remote alias is mandatory. 
Remote url is optional then the message will be fix with` Remote format can follow remoteAlias#[remoteUrl[#position]]`.
Also the message is changed into a information message, for inform developper : `Use existing conan remotes. Remote format can follow remoteAlias#[remoteUrl[#position]] for automatically add unexisting remote`

- Behaviour of `remoteAlias#[remoteUrl[#position]]` : 
It's just for add a conan remote if it not existing : remoteAlias and remoteUrl are not found in conan remote list. 
It's not for update an existing remote with existing alias or url or position.

I'am agree that the behaviour becomes quite unpredictable for multiple projects that have out of sync alias/url, and you can continue to use only remote alias.

**Comment by jim-bcom** [comment]
Sorry to be nit-picky, but just so I understand correctly:
* specifying only the alias triggers the warning message ? (`Use existing conan remotes. Remote format can follow remoteAlias#[remoteUrl[#position]] for automatically add unexisting remote`). I found odd that if only the alias is specified, we get a warning message, which is less a warning than a hint at the developer to know more about the possibility offered by the syntax. My point is that if there is only an alias, the user probably didn't intend to add a remote in the first place, as there is clearly not enough information to do so, so it was probably done on purpose, following the documentation that allows such syntax, so there may be no need to give a warning message. Plus the `Use existing remote` sounds more like an "info" level log to me, maybe to be reserved to a "verbose" mode, what do you think ?
* I have some remarks on the message you suggest:
  * `Use existing conan remotes.`: `Using existing conan remote: <remote alias>` ?
  * `Remote format can follow remoteAlias#[remoteUrl[#position]]`:  you can keep `must` since the syntax definition covers all valid cases.
  *  `for automatically add unexisting remote`
     * `adding` ?
     * maybe don'say this after the first part, as it also describes the case where there's only an alias, which does not add a remote.
     * maybe, in verbose mode, the message could be something like `Using existing conan remote: <remote alias>. Note: remote URL can be specified with remoteAlias#remoteUrl[#position]`
     * the other message, when the URL is specified could also be for verbose mode, `Adding remote <alias> <url> [at <index>]`? 

To conclude, I just found that getting a warning for an intended behavior was a bit unsettling, but if you want to keep it that way (not in verbose mode) to have a better trace to ease debugging, I'm fine with that, I just wanted to be sure I understood the intention.

Thanks for the clarification.

**Comment by stefled** [comment]
Sorry if my last comment is not clear : The message is now an _Information_ message (not a _Warning_ message), and this message is displayed only in verbose mode.

Thanks for the fix on messages, this will be taken in account.
