### ISSUE TITLE
[Architecture] No arm64-v8a available

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/remaken#2]
Architectures name available in Remaken doesn't match [Android ABI](https://developer.android.com/ndk/guides/abis#sa) documentation.

* Add **arm64-v8a** 

![image](https://user-images.githubusercontent.com/22341309/85112181-872aae00-b215-11ea-9032-bc342ce390f8.png)

**Comment by Firefly35** [comment]
Fixed in version https://github.com/b-com-software-basis/remaken/tree/1.6.4
