### ISSUE TITLE
Error when installing remaken with brew

### ISSUE THREAD

**Issue by granger35** [b-com-software-basis/remaken#20]
The brew formula install latest version of conan (version 2) which had replaced --insert by --index to choose the position of a conan remote when adding it (and which add the conancenter remote by default when installing conan).
Need to remove the command `conan remote add --force --insert 0 conancenter https://center.conan.io` in the remaken formula (and if other additions of remote, replace --insert by --index).

**Comment by stefled** [comment]
The brew fomula and the remaken install scripts have been updated in order to not install conan : https://github.com/b-com-software-basis/remaken/releases/tag/Remaken_Linux_Installer_without_conan

conan must be installed separately to avoid problems
