### ISSUE TITLE
Silent failure of 'remaken profile init' when 'remaken init' hasn't been performed

### ISSUE THREAD

**Issue by jillemash** [b-com-software-basis/remaken#22]
**HOW TO REPRODUCE**
* Install remaken for the first time: `brew tap b-com/sft && brew install remaken`
* attempt to create profile with: `remaken profile init --cpp-std 17 -b gcc -o linux -a x86_64`

**EXPECTED BEHAVIOR**
* Either a profile is created in `~/.remaken` or returns an error if it's not possible before calling `remaken init`

**OBSERVED BEHAVIOR**
* `~/.remaken` does not contain a `profiles` directory
* `remaken profile display` returns
```
# remaken
```
* Nothing is printed and exit status is zero, as if everything went well

OS: Ubuntu 22.04
Remaken: 1.9.4

**Comment by stefled** [comment]
Do you have the step to reproduce when `remaken profile init` doesn't contain profile information?

**Comment by jillemash** [comment]
Sorry, I'm not sure I understood you question about the steps to reproduce, but I tried again with a fresh install of remaken 1.10.0 pre-release (from GitHub release page), and it's the same:

```
user@Ubuntu-22:~$ remaken version
1.10.0
user@Ubuntu-22:~$ remaken profile init --cpp-std 17 -b gcc -o linux -a x86_64
user@Ubuntu-22:~$ echo $?
0
user@Ubuntu-22:~$ remaken profile display
# remaken
user@Ubuntu-22:~$ ll ~/.remaken
ls: cannot access '/home/user/.remaken': No such file or directory
```
