### ISSUE TITLE
Misleading "Unknown repository type" error message with artifactory dep pointing to invalid URL

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#24]
**HOW TO REPRODUCE**
* write a packagedepedencies.txt with an invalid URL to an artifactory repo
* run `remaken install`

**EXPECTED BEHAVIOR**
* An error message like a "404" error, with URL trying to be reached.

**OBSERVED BEHAVIOR**
```
=> Installing artifactory::https://<invlid URL to my dep>.zip
[2023-12-08 14:46:43.652487] [0x00007fd7a2346d80] [error]   Unknown repository type 
```

This is (a bit) misleading because `artifactory` is a known repository type, so we don't actually know that there's in fact a typo in the URL.

**Comment by stefled** [comment]
same fix as #25 

will be available in release 1.10.0
