### ISSUE TITLE
Erroneous link mode is silently ignored

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#25]
**HOW TO REPRODUCE**
* Use the following packagedepedencies.txt with an invalid link mode:
```
SolARFramework|1.0.0|SolARFramework|SolARBuild@github|https://github.com/SolarFramework/SolARFramework/releases/download|unknownlinkmode|
```
* run remaken install

**EXPECTED BEHAVIOR** 
* An error message like 
```
"Error: unknown link mode: 'unknownlinkmode' for SolARFramework (packagedependencies.txt - line: 1)"
```

**OBSERVED BEHAVIOR**
```
=> Installing github::https://github.com/SolarFramework/SolARFramework/releases/download/SolARFramework/1.0.0/linux/SolARFramework_1.0.0_x86_64_shared_release.zip
[... installs dependency...]
```
When an unkown link mode is encountered, remaken seems to fallback to `shared` here.

I may add that if the link mode is known, but the resource does not exist, e.g. if we use `static` link mode with our dep example, we have a `Unkown repository type` error (along with 404 errors) that is not relevant here as the reposotory type `github` is correct.

Besides, when the repository type is indeed wrong, the error message is correct:

```
SolARFramework|1.0.0|SolARFramework|SolARBuild@wrongrepotype|https://github.com/SolarFramework/SolARFramework/releases/download|static
```

```
2023-12-08 15:10:01.064268] [0x00007f4b24cffd80] [error]   Dependency file error : invalid repository type : unsupported value= wrongrepotype
Dependency =>
    name=SolARFramework
    version=1.0.0
    type=wrongrepotype
    link mode=static
    identifier=SolARBuild
    channel=stable

[2023-12-08 15:10:01.064327] [0x00007f4b24cffd80] [error]   Error parsing dependency file : invalid format
```

**Comment by stefled** [comment]
Any unsupported mode is replaced by the default mode (shared in this case). 
This management will not change to an error, but a message will be displayed to warn. For instance : 

`[WARNING] current mode 'unknownlinkmode' is unsupported for 'SolARFramework' dependency, then apply 'shared'default mode`

Iif the link mode is known, but the resource does not exist, e.g. if we use static link mode with your dep example, the will be a fix : 

```
[INFO]: No alternate handler found
[2023-12-11 15:24:56.966332] [0x0000061c] [error]   ==> Unable to find 'SolARFramework:1.0.0' in 'static' mode on github('https://github.com/SolarFramework/SolARFramework/releases/download')
```

The previous management with error comes from there is no alternate repository, then this error has been changed as an INFO message, and an error occured after when try to download the resource that not exists.
