### ISSUE TITLE
[Encoding] Packagedependencies readings

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/remaken#5]
If a `packagedependencies.txt` have been **saved on Windows** and **have carriage return (encoded by Windows)** `remaken install` encounters `Segmentation fault` error.

![image](https://user-images.githubusercontent.com/22341309/94036076-31d9dc00-fdc4-11ea-9c7e-3b7c87260a05.png)

**Comment by stefled** [comment]
Issue not encountered on the latest version and possibly corrected for a while

Issue closed - Need to be reopen if it is reproduced by someone
