### ISSUE TITLE
[Conan] Should ignore remaken-cache

### ISSUE THREAD

**Issue by RealVincentBerthet** [b-com-software-basis/remaken#6]
As Conan can detect if an install of `packagedependencies.txt` already exists on the system it will be better to use this feature instead of a dedicated cache.

Remove a Conan package and forget to remove the install line in the `remaken-cache` is a source of mistakes. 
==> Remaken should call Conan in every case and let Conan manage his packages.

**Comment by stefled** [comment]
add ignoring conan dependencies in remaken cache
fix empty lines in .remaken-cache file

enhancement available in next version 1.10.0
