### ISSUE TITLE
Feature request: add option to force replacing existing files

### ISSUE THREAD

**Issue by jim-bcom** [b-com-software-basis/remaken#9]
Platform: Linux

HOW TO REPRODUCE
```
$ remaken install packagedependencies.txt
$ remaken install -c debug packagedependencies.txt
```

EXPECTED BEHAVIOR
Everything installs automatically.

OBSERVED BEHAVIOR
Installation of debug package stops and asks the user to decide what to do with files that already exist.

Ex:
```
=> Installing github::https://github.com/path/to/my/lib_debug.zip
replace /home/user/.remaken/packages/path/to/my/already/installed/release/lib/packagedependencies.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

This does not seem to happen on Windows.
This message is likely due to the 'unzip' command.

Maybe overwriting files silently is a bit dangerous, but adding the opportunity to the user to do so might be nice.

This can be done with 'unzip -o' option (+ quiet/verbose).

**Comment by Firefly35** [comment]
This is supported through the --override flag (or -e) available for the install command (remaken install -h will display additionnal options for the install command.
